global:
  scrape_interval: 5s
  evaluation_interval: 5s


scrape_configs:
  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9192'] # Update the port and host as necessary
  - job_name: 'payment'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9191'] # Update the port and host as necessary